services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.7.2@sha256:1476924357b46e80735c13e94232ba5c853cac052e9df4bb28d50fa56348097b
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=America/Chicago
    volumes:
      - ./homeassistant/config:/config
    ports:
      - "8123:8123"

  cloudflared:
    image: cloudflare/cloudflared:2026.9.1@sha256:b269e8abd07a5bf6f3f4be65d5050b2174eca89c56a0241a8ff32a16aec454e4
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate --protocol http2 run --token ${CLOUDFLARED_TOKEN}

  homarr:
    image: ghcr.io/homarr-labs/homarr:latest@sha256:f0fb462299af9749a72f11040fd3f604d1c4976b3d9a137ae5021b7f44d980f5
    container_name: homarr
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_ENCRYPTION_KEY}
    volumes:
      - ./homarr/appdata:/appdata
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "7575:7575"

  uptime-kuma:
    image: louislam/uptime-kuma:1.23.17@sha256:3d632903e6af34139a37f18055c4f1bfd9b7205ae1138f1e5e8940ddc1d176f9
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    dns:
      - 192.168.1.174
      - 1.1.1.1
    volumes:
      - ./uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
