services:
  retro-games:
    image: nginx:alpine@sha256:1ed1b0e1d7652937d6cbdaf4018c7b6fc009a7dd6c3047351e2eddda745de43f
    container_name: retro-games
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
