services:
  retro-games:
    image: nginx:alpine@sha256:df221db836e1754089190208cee7eeda94f233197056426eda74a43ab1abeac2
    container_name: retro-games
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
